### ISSUE TITLE
Add a Map

### ISSUE THREAD

**Issue by spaceysteven** [Creaous/ImpostersMC-Skript#12]
I believe that adding a map would be a beneficial feature as some players, including myself, may get lost trying to find their tasks. But, this is completely up to you to consider adding.

**Comment by Creaous** [comment]
Might be added in v1.0.0-beta.4 if not probably in v1.0.0-beta.5.

**Comment by Creaous** [comment]
I don't really know how to add a map that is already made to a player's inventory yet. That's why I am applying the help wanted label. Please reply with helpful information if you have any.

**Comment by Creaous** [comment]
Added in v1.0.0-beta.5 as an empty map for the moment.
