### ISSUE TITLE
Ejection not stopping game

### ISSUE THREAD

**Issue by spaceysteven** [Creaous/ImpostersMC-Skript#13]
In this bug, after ejecting all players besides the imposter, the game does not end. I know you are aware of this, but why not put it here?

Steps to reproduce:
1. Start the game.
2. Call an Emergency Meeting.
3. Eject someone.
4. Repeat until everyone besides the imposter is ejected.

Expected behavior:
The game ends.

Screenshots:
I have none about this issue.

**Comment by Creaous** [comment]
Since the priority is high, it will probably be fixed in v1.0.0-beta.4.
